<head>
  <meta HTTP-EQUIV="Content-Type" CONTENT="text/html;charset=UTF-8">
  <title>MyFaces - the free JSF Implementation</title>
  <link rel="stylesheet" type="text/css" href="css/basic.css">
  
  <!-- JSCook Menu -->
  <script language="JavaScript" src="jscookmenu/JSCookMenu.js" type="text/javascript"></script>
  <script language="JavaScript" src="jscookmenu/ThemeOffice/theme.js"></script>
  <link rel="stylesheet" href="jscookmenu/ThemeOffice/theme.css" type="text/css">
  <script language="JavaScript" src="jscookmenu/ThemeMiniBlack/theme.js"></script>
  <link rel="stylesheet" href="jscookmenu/ThemeMiniBlack/theme.css" type="text/css">
  <script language="JavaScript" src="jscookmenu/ThemeIE/theme.js"></script>
  <link rel="stylesheet" href="jscookmenu/ThemeIE/theme.css" type="text/css">
  <script language="JavaScript" src="jscookmenu/ThemePanel/theme.js"></script>
  <link rel="stylesheet" href="jscookmenu/ThemePanel/theme.css" type="text/css">

</head>
